force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/DeletedDate__c.field-meta.xml
<CustomField>
    <fullName>DeletedDate__c</fullName>
    <label>DeletedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fields__c/Fields__c.object-meta.xml
<CustomObject>
    <label>Field</label>
    <nameField>
        <label>Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fields__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fields__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <label>OrderNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/CompletedPercentage__c.field-meta.xml
<CustomField>
    <fullName>CompletedPercentage__c</fullName>
    <label>CompletedPercentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/DeletedDate__c.field-meta.xml
<CustomField>
    <fullName>DeletedDate__c</fullName>
    <label>DeletedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <referenceTo>Fields__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketNumber__c.field-meta.xml
<CustomField>
    <fullName>TicketNumber__c</fullName>
    <label>TicketNumber</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketPriority__c.field-meta.xml
<CustomField>
    <fullName>TicketPriority__c</fullName>
    <label>TicketPriority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HomePage.cls
/*******************************************************
* Name          : HomePage
* Author        : Nimit Shah
* Create Date   : 12/08/2022
* UsedBy        : Used by home.js 
* Description   : Use this class to do CRUD Operation on Board Object
* Test Class    : 
*******************************************************/
public with sharing class HomePage {
    
     /**
     * @description getBoards Method
     * @return boards It returns List of Board__c 
     */
    @AuraEnabled
    public static List<Board__c> getBoards(){

        try{

            List<Board__c> boards = [SELECT Id,Name,DeletedDate__c,CreatedDate,Description__c FROM Board__c WITH SECURITY_ENFORCED order by LastModifiedDate asc];
            List<Ticket__c> tickets = [SELECT Id, Name, TicketPriority__c,CreatedDate,LastModifiedDate, Field__c, Field__r.Name,Color__c, Description__c, DeletedDate__c, CompletedPercentage__c,StartDate__c,EndDate__c,TicketNumber__c FROM Ticket__c WHERE DeletedDate__c < LAST_N_DAYS:15 WITH SECURITY_ENFORCED order by LastModifiedDate asc ];

            // List<Fields__c> fields = [SELECT Id, Name, OrderNumber__c, Board__c FROM Fields__c ORDER BY OrderNumber__c ASC];
            // List<Comment__c> comments = [SELECT Id, Name,Comments__c,Ticket__c FROM Comment__c];

            // To delete the 15 day old deleted board
            List<Board__c> deleteboard = new List<Board__c>();

            Date startDate = Date.today();
            Date endDate;
            Integer days;
            
            for(integer i = 0; i < boards.size(); i++ ){
                if(boards[i].DeletedDate__c != null){
                    endDate = date.newinstance( boards[i].DeletedDate__c.year(),  boards[i].DeletedDate__c.month(),  boards[i].DeletedDate__c.day());
                    days = startDate.daysBetween( endDate );
                    if(days < -15){
                        deleteboard.add(boards[i]);
                        boards.remove(i);
                    }
                }
            }
            delete deleteboard;             // To delete the 15 day old deleted board.

            delete tickets;                 // To delete the 15 day old deleted ticket.
           
            return boards;
        }
        catch(Exception e){
            HandleExceptions eh = new HandleExceptions(e);
            return null;
        }
    }

    /**
     * @description createboard Method
     * @param board Record of Board__c Object
     * @return newboard It returns Board__c 
     */
    @AuraEnabled
     public static Board__c createboard(Board__c board){
        try {

            Board__c newboard = new Board__c();
            newboard.Name = board.Name;
            newboard.Description__c = board.Description__c;

            insert as User newboard;
            
            return newboard;

        } catch (Exception e) {
            HandleExceptions eh = new HandleExceptions(e);
            return null;
        }
    }

         /**
     * @description deleteboard Method
     * @param searchkey Id of Board__c
     * @Return boards It is List of Board__c
     */
    @AuraEnabled
    public static List<Board__c> searchBoard(String searchkey){
        try{

            List<Board__c> boards = new List<Board__c>(); 
            if (searchkey != null) {
                searchkey = '%' + searchkey + '%';
                boards = [SELECT Id,Name,DeletedDate__c,CreatedDate,Description__c FROM Board__c WHERE Name LIKE: searchkey AND DeletedDate__c =: null WITH SECURITY_ENFORCED order by LastModifiedDate asc];
            } else {
                boards = [SELECT Id,Name,DeletedDate__c,CreatedDate,Description__c FROM Board__c WHERE DeletedDate__c =: null WITH SECURITY_ENFORCED order by LastModifiedDate asc];
            }
            return boards;

        } catch(Exception e){
            HandleExceptions eh = new HandleExceptions(e);
            return null;
        }
    }


     /**
     * @description deleteboard Method
     * @param boardId Id of Board__c
     */
    @AuraEnabled
    public static void deleteboard(Id boardId){
        try{

            Board__c deleteboard = new Board__c (Id = boardId, DeletedDate__c = System.today());
            upsert as User deleteboard;
            
        } catch(Exception e){
            HandleExceptions eh = new HandleExceptions(e);
        }
    }

     /**
     * @description restoreboard Method
     * @param boardId Id of Board__c
     */
    @AuraEnabled
    public static void restoreboard(Id boardId){
        try{

            Board__c restoreboard = new Board__c (Id = boardId, DeletedDate__c = null);
            upsert as User restoreboard;

        } catch(Exception e){
            HandleExceptions eh = new HandleExceptions(e);
        }
    }

     /**
     * @description permanentdeleteboard Method
     * @param boardId Id of Board__c
     */
    @AuraEnabled
    public static void permanentdeleteboard(Id boardId){
        try{
                Board__c b = new Board__c(Id = boardId);
                delete as User b;
        } catch(Exception e){
            HandleExceptions eh = new HandleExceptions(e);
            System.debug(e);
        }
    }

}