force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/DeletedDate__c.field-meta.xml
<CustomField>
    <fullName>DeletedDate__c</fullName>
    <label>DeletedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fields__c/Fields__c.object-meta.xml
<CustomObject>
    <label>Field</label>
    <nameField>
        <label>Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fields__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fields__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <label>OrderNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/DeletedDate__c.field-meta.xml
<CustomField>
    <fullName>DeletedDate__c</fullName>
    <label>DeletedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <referenceTo>Fields__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketNumber__c.field-meta.xml
<CustomField>
    <fullName>TicketNumber__c</fullName>
    <label>TicketNumber</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketPriority__c.field-meta.xml
<CustomField>
    <fullName>TicketPriority__c</fullName>
    <label>TicketPriority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/viewBoard.cls
public class viewBoard {

    @AuraEnabled
    public static FieldTicketwrapper getBoardData(Id boardId){
        try {
            List<Fields__c> fieldList = [SELECT Id, Name, OrderNumber__c, Board__c FROM Fields__c  WHERE Board__c =: boardId WITH SECURITY_ENFORCED ORDER BY OrderNumber__c ASC];
            List<Ticket__c> ticketList = [SELECT Id, Name, TicketNumber__c, TicketPriority__c, DeletedDate__c, Field__c, Color__c, CreatedDate FROM Ticket__c WHERE Field__c IN: fieldList WITH SECURITY_ENFORCED];

            FieldTicketwrapper ftw = new FieldTicketwrapper();
            ftw.fieldList = fieldList;
            ftw.ticketList = ticketList;
            return ftw;
        } catch (Exception e) {
            HandleExceptions eh = new HandleExceptions(e);
            return null;
        }
    }

    //It is call when someone create ticket
    @AuraEnabled
    public static Ticket__c createticket(Ticket__c newticket){
        try{
            Ticket__c ticket = new Ticket__c (TicketNumber__c = newticket.TicketNumber__c, Name = newticket.Name, Description__c = newticket.Description__c, StartDate__c  = newticket.StartDate__c, EndDate__c =  newticket.EndDate__c, TicketPriority__c  = newticket.TicketPriority__c, Field__c = newticket.Field__c, Color__c = newticket.Color__c);
            insert ticket;
            return ticket;
        } catch(Exception e){
            System.debug(e);
            HandleExceptions eh = new HandleExceptions(e);
            return null; 
        }
    }

    // It is call when someone drag and drop ticket
    @AuraEnabled
    public static void updateticketfield(Id ticketId, Id fieldId){
        try{
        Database.upsert(new Ticket__c (Id = ticketId, Field__c = fieldId));
        } catch (Exception e){
            System.debug(e);
            HandleExceptions eh = new HandleExceptions(e);
        }
    }

    @AuraEnabled
    public static void temporarydeleteticket(Id ticketId){
        try {
            Database.upsert(new Ticket__c(Id = ticketId, DeletedDate__c = System.today()));
        } catch (Exception e) {
            HandleExceptions eh = new HandleExceptions(e);
        }
    }

    @AuraEnabled
    public static void restoreticket(Id ticketId){
        try {
            Database.upsert(new Ticket__c(Id = ticketId, DeletedDate__c = null));
        } catch (Exception e) {
            HandleExceptions eh = new HandleExceptions(e); 
        }
    }

    @AuraEnabled
    public static void permanentdeleteticket(Id ticketId){
        try {
            Database.delete(ticketId);
        } catch (Exception e) {
            HandleExceptions eh = new HandleExceptions(e);   
        }
    }

    public class FieldTicketwrapper{
        @AuraEnabled
        public List<Fields__c> fieldList {get; set;}
        @AuraEnabled
        public List<Ticket__c> ticketList {get; set;}
    }
}