force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fields__c/Fields__c.object-meta.xml
<CustomObject>
    <label>Field</label>
    <nameField>
        <label>Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fields__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fields__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <label>OrderNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/fieldController.cls
public with sharing class fieldController {
    
    @AuraEnabled
    public static List<Fields__c> getFields (Id boardId) {
        try {
            return [SELECT Id, Name, OrderNumber__c FROM Fields__c WHERE Board__c =: boardId ORDER BY OrderNumber__c ASC];
        } catch (Exception e) {
            System.debug(e);
            return null;
        }
    }

    @AuraEnabled
    public static List<Fields__c> createfield(Fields__c field, Id boardid){
        try {
            List<Fields__c> fieldList = new List<Fields__c>();
            fieldList = [SELECT Id, Name, OrderNumber__c FROM Fields__c WHERE Board__c =: boardid ORDER BY OrderNumber__c ASC];
            if (field.OrderNumber__c == null) {
                field.OrderNumber__c = fieldList.size() + 1;
                fieldList.add(field);
            } else {
                Integer n = 0;
                Integer newFieldIndex = null; 
                for (Fields__c fields : fieldList) {
                    if (fields.OrderNumber__c ==  field.OrderNumber__c) {
                        newFieldIndex = n;
                        n = (Integer)fields.OrderNumber__c;
                    }
                    n++;
                    fields.OrderNumber__c = n;
                }
                if (newFieldIndex != null) {
                    fieldList.add(newFieldIndex, field);
                } else {
                    fieldList.add(field);
                }
            }
            upsert fieldList;
            return fieldList;
        } catch (Exception e) {
            System.debug(e);
            HandleExceptions eh = new HandleExceptions(e);
            return null;
        }
    }
}