force-app/main/default/objects/Error_Handler__c/Error_Handler__c.object-meta.xml
<CustomObject>
    <label>Error Handler</label>
    <nameField>
        <displayFormat>WB-{00000}</displayFormat>
        <label>Error Handler Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Handler__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Handler__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Handler__c/fields/More_Details__c.field-meta.xml
<CustomField>
    <fullName>More_Details__c</fullName>
    <label>More Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HandleExceptions.cls
/*******************************************************
* Name          : HandleExceptions
* Author        : Nimit Shah
* Create Date   : 22/08/2022
* UsedBy        : Used by all the classes of WorkBoard 
* Description   : Call this class when exception occur in any other classes of WorkBoard
* Test Class    : HandleExceptionTest
*******************************************************/

/**
 * @description HandleExceptions Class
 */
public with sharing class HandleExceptions {

    /**
     * @description HandleExceptions Method
     * @param e It is Exception 
     */
    public static void handleExceptionsmethod(Exception e) {

        String stackTrace = e.getStackTraceString().substringBefore('\n');
        String className = stackTrace.substringAfter('GB_24.').substringBefore('.');	
        String methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');
        Error_Handler__c eh = new Error_Handler__c();
        try {            
            eh.Class_Name__c = classname;
            eh.Method_Name__c = methodName;
            eh.Exception_Message__c = e.getMessage();
            eh.Exception_Type__c = e.getTypeName();
            eh.Line_Number__c = e.getLineNumber();
            eh.More_Details__c = e.getStackTraceString();

            insert as User eh;

        } catch (Exception error) {
            eh.Class_Name__c = 'HandleExceptions';
            insert as User eh;
        }
    }
}